# Home Assistant Automation Examples
# Copy these to your automations.yaml or include via packages

# Example 1: Motion-Activated Lights with Brightness Based on Time
automation:
  - id: "motion_lights_living_room_001"
    alias: "Motion Lights - Living Room"
    description: "Turn on lights when motion detected, brightness varies by time of day"
    mode: restart
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        entity_id: binary_sensor.motion_living_room
        to: "on"
    conditions:
      - condition: numeric_state
        entity_id: sensor.living_room_illuminance
        below: 50
    actions:
      - action: light.turn_on
        target:
          entity_id: light.living_room
        data:
          brightness_pct: >
            {% if now().hour >= 22 or now().hour < 6 %}
              30
            {% elif now().hour >= 6 and now().hour < 8 %}
              50
            {% else %}
              100
            {% endif %}
          transition: 2
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.motion_living_room
            to: "off"
            for:
              minutes: 5
        timeout:
          minutes: 30
      - action: light.turn_off
        target:
          entity_id: light.living_room
        data:
          transition: 5

  # Example 2: Presence-Based Thermostat
  - id: "thermostat_presence_001"
    alias: "Thermostat - Away Mode"
    description: "Set thermostat to away mode when everyone leaves"
    mode: single
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        entity_id: group.family
        to: "not_home"
        for:
          minutes: 10
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    actions:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          temperature: 18
      - action: notify.mobile_app
        data:
          message: "Everyone left. Thermostat set to away mode (18°C)"
          title: "Home Status"

  # Example 3: Thermostat - Return Home
  - id: "thermostat_presence_002"
    alias: "Thermostat - Home Mode"
    description: "Set thermostat to home mode when someone arrives"
    mode: single
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        entity_id: group.family
        to: "home"
    actions:
      - action: climate.set_temperature
        target:
          entity_id: climate.thermostat
        data:
          temperature: 21
      - action: notify.mobile_app
        data:
          message: "Welcome home! Thermostat set to 21°C"
          title: "Home Status"

  # Example 4: Doorbell with Actionable Notification
  - id: "doorbell_notification_001"
    alias: "Doorbell - Send Notification"
    description: "Send notification with camera snapshot when doorbell pressed"
    mode: single
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        entity_id: binary_sensor.doorbell
        to: "on"
    actions:
      - action: notify.mobile_app
        data:
          title: "Doorbell"
          message: "Someone is at the door"
          data:
            actions:
              - action: "UNLOCK_DOOR"
                title: "Unlock Door"
              - action: "IGNORE"
                title: "Ignore"
            image: /api/camera_proxy/camera.front_door

  # Example 5: Handle Doorbell Action
  - id: "doorbell_action_001"
    alias: "Doorbell - Handle Unlock Action"
    description: "Unlock door when notification action is pressed"
    mode: single
    trace:
      stored_traces: 10
    triggers:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: "UNLOCK_DOOR"
    actions:
      - action: lock.unlock
        target:
          entity_id: lock.front_door
      - action: notify.mobile_app
        data:
          message: "Door unlocked"
          title: "Security"

  # Example 6: Daily Backup
  - id: "backup_daily_001"
    alias: "System - Daily Backup"
    description: "Create automated backup every day at 3 AM"
    mode: single
    trace:
      stored_traces: 5
    triggers:
      - trigger: time
        at: "03:00:00"
    actions:
      - action: backup.create
        data:
          name: "auto_{{ now().strftime('%Y%m%d') }}"
      - action: notify.mobile_app
        data:
          message: "Daily backup created successfully"
          title: "System"

  # Example 7: Low Battery Alert
  - id: "battery_alert_001"
    alias: "Alert - Low Battery"
    description: "Send notification when any sensor battery is low"
    mode: queued
    max: 10
    trace:
      stored_traces: 10
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.motion_sensor_battery
          - sensor.door_sensor_battery
          - sensor.temperature_sensor_battery
        below: 20
    actions:
      - action: notify.mobile_app
        data:
          title: "Low Battery Alert"
          message: "{{ trigger.to_state.attributes.friendly_name }} battery is at {{ trigger.to_state.state }}%"

  # Example 8: Sunset Lights
  - id: "sunset_lights_001"
    alias: "Lighting - Sunset"
    description: "Turn on exterior lights at sunset"
    mode: single
    trace:
      stored_traces: 5
    triggers:
      - trigger: sun
        event: sunset
        offset: "-00:15:00"
    conditions:
      - condition: state
        entity_id: binary_sensor.home_occupied
        state: "on"
    actions:
      - action: light.turn_on
        target:
          entity_id:
            - light.porch
            - light.pathway
        data:
          brightness_pct: 80

  # Example 9: Sunrise Lights Off
  - id: "sunrise_lights_001"
    alias: "Lighting - Sunrise"
    description: "Turn off exterior lights at sunrise"
    mode: single
    trace:
      stored_traces: 5
    triggers:
      - trigger: sun
        event: sunrise
        offset: "00:15:00"
    actions:
      - action: light.turn_off
        target:
          entity_id:
            - light.porch
            - light.pathway

  # Example 10: Window Open Climate Alert
  - id: "window_climate_001"
    alias: "Alert - Window Open with Climate Running"
    description: "Alert when window is open while HVAC is running"
    mode: single
    trace:
      stored_traces: 10
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_window
        to: "on"
        for:
          minutes: 5
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.thermostat
            state: "off"
    actions:
      - action: notify.mobile_app
        data:
          title: "Energy Alert"
          message: "Living room window has been open for 5 minutes while HVAC is running"
      - action: persistent_notification.create
        data:
          title: "Window Alert"
          message: "Close the window or turn off HVAC to save energy"
          notification_id: "window_climate_alert"
